#########
# Reuse #
#########
variables:
  RUNNER_IMAGE: docker:20
  ARTIFACT_IMAGE: registry.gitlab.com/gisleburt/rust-builder

##########
# Stages #
##########
stages:
  - build

#########
# Build #
#########
.docker-build: &docker-build
  stage: build
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_TLS_VERIFY: 1
  services:
    - docker:dind
  before_script:
    - while [ ! -f /certs/client/ca.pem ]; do sleep 1; done
    - ls -R /certs
    - while ! docker info; do sleep 1; done
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-linux-arm64:
  <<: *docker-build
  tags:
    - linux
    - arm64
  stage: build
  script:
    - docker build . -t $ARTIFACT_IMAGE
    - docker push $ARTIFACT_IMAGE
    - RUST_VERSION=$(docker run --rm $ARTIFACT_IMAGE sh -c "rustc --version | awk '{ print \$2 }'")
    - docker tag $ARTIFACT_IMAGE $ARTIFACT_IMAGE:$RUST_VERSION
    - docker push $ARTIFACT_IMAGE:$RUST_VERSION
