#########
# Reuse #
#########
variables:
  ARTIFACT_IMAGE: registry.gitlab.com/gisleburt-homelab/rust-builder

##########
# Stages #
##########
stages:
  - build

#########
# Build #
#########
.docker-build: &docker-build
  stage: build
  image: docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_TLS_VERIFY: 1
  services:
    - name: docker:dind
      command: ["--mtu=1300"]
  before_script:
    - echo Waiting on docker...
    - while ! docker info > /dev/null 2>&1; do sleep 1; done
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-linux-arm64:
  <<: *docker-build
  tags:
    - linux
    - arm64
    - gisleburt
    - homelab
  stage: build
  script:
    - docker build . -t $ARTIFACT_IMAGE
    - RUST_VERSION=$(docker run --rm $ARTIFACT_IMAGE sh -c "rustc --version | awk '{ print \$2 }'")
    - docker tag $ARTIFACT_IMAGE $ARTIFACT_IMAGE:$RUST_VERSION
    - docker push $ARTIFACT_IMAGE:$RUST_VERSION
